version: "3"
services:
  node:
    image: node:16.19.0-alpine3.16
    working_dir: /workspace
    volumes:
      - .:/workspace
      - node-module-volume:/workspace/node_modules
    ports:
      - 3000:3000
    command: "yarn dev"
volumes:
  node-module-volume:
